build: false

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

build_script:
  - "%PYTHON%/Scripts/pyinstaller.exe dstimer_server.spec"

test_script:
  - "%PYTHON%/python.exe dstimer_test.py"

artifacts:
  - path: dist/*.exe
    name: Executable
